services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="ny_taxi"
    volumes:
      - /home/thantko/postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL="admin@admin.com"
      - PGADMIN_DEFAULT_PASSWORD="password"
    ports:
      - 8080:80